import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import { Router, useRouter } from "next/router";
import { useAuth, SignIn } from "@clerk/nextjs";
import { Icon } from "@iconify/react";

// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const pathname  = router.pathname;
  const { isLoaded, userId } = useAuth();
  if (!userId && pathname !== "/"){
		router.push("/")
  }
  if (!isLoaded || !userId) {
    return (
      <>
        <Head>
          <title>Bevary</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="drinkBackground slideBottomFadeIn">
          <Image
            src="/icon-background.jpg"
            layout="fill"
            objectFit="cover"
            alt="background photo of drinks"
          />
        </div>
        <div className="slideTopFadeIn">
          <Header title={"Bevary"} />
          <div class="section is-centered">
            <div class="hero is-link py-4 centerText">
              <h3 class="title">Welcome to Bevary!</h3>
              <h4 class="subtitle is-5">Please Sign-In</h4>
            </div>
          </div>
        </div>
        <div className="fadeIn centerElement">
          <SignIn />
        </div>
      </>
    );
  } else {
    router.push("/map");
  }
}
